#!/usr/bin/env -S gjs -m
// WeatherCore parity + policy tests for the GJS port. Runs the pure modules
// under plain `gjs` (no Shell) against the SAME fixtures the Swift tests use
// (../../Tests/WeatherCoreTests/Fixtures, generated by scripts/gen-fixtures.js
// from the reference Pebble JS). Usage:  gjs -m gnome/tests/run.js

import GLib from 'gi://GLib';

const here = GLib.path_get_dirname(GLib.filename_from_uri(import.meta.url)[0]);
// Fixtures: the copy beside the tests (kept in sync from
// Tests/WeatherCoreTests/Fixtures so the gnome/ folder is self-contained when
// vendored elsewhere); fall back to the Swift tests' originals.
const fixturesDir = [
    GLib.build_filenamev([here, 'fixtures']),
    GLib.build_filenamev([here, '..', '..', 'Tests', 'WeatherCoreTests', 'Fixtures']),
].find(d => GLib.file_test(GLib.build_filenamev([d, 'wmo.json']), GLib.FileTest.EXISTS));
const coreDir = GLib.build_filenamev([here, '..', 'touchyweather@clickcalickclick.github.io', 'weathercore']);
const core = name => import(`file://${coreDir}/${name}`);

const {Condition, Severity, makeLocation, LocationKind} = await core('models.js');
const {conditionForWMO} = await core('wmo.js');
const {compass, uvLabel, aqiLabel} = await core('labels.js');
const {moonPhase, goldenHours} = await core('astronomy.js');
const {rainAlertMinutes, pollenUPI, isEurope} = await core('derived.js');
const {startIndex} = await core('hourWindow.js');
const {assemble} = await core('assembler.js');
const {CachePolicy} = await core('cachePolicy.js');
const {Backoff} = await core('backoff.js');
const {planNotifications, makeNotificationSettings} = await core('notificationPlanner.js');
const {LocationsFile, NotificationDedupState} = await core('persistence.js');
const {alertFromProperties} = await core('providers/nws.js');
const {RadarTileMath} = await core('radarTileMath.js');

// ---- tiny harness ----------------------------------------------------------
let passed = 0, failed = 0;
const failures = [];
function expect(cond, label) {
    if (cond) passed++;
    else { failed++; failures.push(label); }
}
const eq = (a, b, label) => expect(a === b, `${label}: got ${JSON.stringify(a)}, want ${JSON.stringify(b)}`);
function fixture(name) {
    const [ok, bytes] = GLib.file_get_contents(GLib.build_filenamev([fixturesDir, `${name}.json`]));
    if (!ok) throw new Error(`missing fixture ${name}`);
    return JSON.parse(new TextDecoder().decode(bytes));
}
const iso = s => Date.parse(s) / 1000;
const suites = [];
const suite = (name, fn) => suites.push([name, fn]);

// ---- FormulaParityTests ----------------------------------------------------
suite('wmoMappingParity', () => {
    const cases = fixture('wmo');
    eq(cases.length, 100, 'wmo case count');
    for (const c of cases) eq(conditionForWMO(c.code), c.condition, `WMO ${c.code}`);
});
suite('compassParity', () => {
    for (const c of fixture('compass')) eq(compass(c.deg), c.dir, `bearing ${c.deg}`);
});
suite('moonPhaseParity', () => {
    for (const c of fixture('moon')) {
        const m = moonPhase(iso(c.date));
        eq(m.phase, c.phase, `phase @ ${c.date}`);
        eq(m.illumination, c.illum, `illum @ ${c.date}`);
        eq(m.name1, c.name1, `name1 @ ${c.date}`);
        eq(m.name2, c.name2, `name2 @ ${c.date}`);
    }
});
suite('goldenHourParity', () => {
    for (const c of fixture('golden')) {
        const g = goldenHours(iso(c.date), c.lat, c.lng);
        for (const k of ['blueAM', 'goldAM', 'goldPM', 'bluePM']) {
            if (c[k] === null) eq(g[k], null, `${k} @ ${c.date} (polar null)`);
            else expect(g[k] !== null && Math.abs(g[k] - c[k]) < 0.01, `${k} @ ${c.date}: got ${g[k]}, want ${c[k]}`);
        }
    }
});
suite('pollenUPIParity', () => {
    for (const c of fixture('pollen')) {
        const got = pollenUPI(c);
        eq(got, c.upi < 0 ? null : c.upi, `pollen grass=${c.grass}`);
    }
});
suite('rainAlertParity', () => {
    for (const c of fixture('rain'))
        eq(rainAlertMinutes(c.amounts), c.minutes < 0 ? null : c.minutes, `rain ${JSON.stringify(c.amounts)}`);
});

// ---- AssemblerTests --------------------------------------------------------
const sf = makeLocation({kind: LocationKind.SAVED, name: 'San Francisco', admin1: 'California', countryCode: 'US', latitude: 37.7749, longitude: -122.4194});
suite('assemblesCurrentConditions', () => {
    const snap = assemble({location: sf, units: 0, forecast: fixture('om-forecast'), airQuality: fixture('om-airquality'), fetchedAt: Date.now() / 1000});
    eq(snap.temperature, 68.9, 'temperature');
    eq(snap.feelsLike, 66.3, 'feelsLike');
    eq(snap.condition, Condition.SUNNY, 'condition');
    eq(snap.isDay, true, 'isDay');
    eq(snap.humidity, 55, 'humidity');
    eq(snap.windDirection, 'W', 'windDirection');
    eq(snap.utcOffsetSeconds, -25200, 'utcOffset');
    eq(snap.timezoneIdentifier, 'America/Los_Angeles', 'timezone');
});
suite('windowsHourlyAndDaily', () => {
    const snap = assemble({location: sf, units: 0, forecast: fixture('om-forecast'), airQuality: null, fetchedAt: Date.now() / 1000});
    eq(snap.hourly.length, 24, 'hourly count');
    eq(snap.daily.length, 7, 'daily count');
    eq(snap.precipProbNext5.length, 5, 'precip5 count');
    eq(snap.hourly[0].time, 1_784_235_600, 'first hourly instant');
});
suite('mergesAirQualityAndSuppressesNonEuropePollen', () => {
    const snap = assemble({location: sf, units: 0, forecast: fixture('om-forecast'), airQuality: fixture('om-airquality'), fetchedAt: Date.now() / 1000});
    eq(snap.aqi, 51, 'aqi');
    eq(snap.pm25, 10, 'pm25 rounds 9.6→10');
    eq(snap.pollenLevel, null, 'non-Europe pollen nil');
});
suite('degradesWhenAirQualityMissing', () => {
    const snap = assemble({location: sf, units: 0, forecast: fixture('om-forecast'), airQuality: null, fetchedAt: Date.now() / 1000});
    eq(snap.aqi, null, 'aqi nil');
    eq(snap.pm25, null, 'pm25 nil');
    eq(snap.temperature, 68.9, 'forecast intact');
});
suite('sunriseParsedWithLocationOffset', () => {
    const snap = assemble({location: sf, units: 0, forecast: fixture('om-forecast'), airQuality: null, fetchedAt: Date.now() / 1000});
    eq(snap.sunrise, 1_784_206_800, 'sunrise instant');
});

// ---- PolicyTests -----------------------------------------------------------
suite('freshnessGate', () => {
    const now = 1_000_000;
    expect(CachePolicy.isFresh(now - 14 * 60, now), 'fresh at 14m');
    expect(!CachePolicy.isFresh(now - 15 * 60, now), 'stale at 15m');
    expect(!CachePolicy.isFresh(now - 60 * 60, now), 'stale at 60m');
});
suite('backoffDelaySequence', () => {
    [0, 5, 10, 20, 40, 80, 160, 240, 240, 240].forEach((mins, n) => eq(Backoff.delay(n), mins * 60, `n=${n}`));
    eq(Backoff.delay(100), 240 * 60, 'n=100 capped');
    eq(Backoff.delay(1000), 240 * 60, 'n=1000 capped');
});
suite('backoffMayRetry', () => {
    const t0 = 2_000_000;
    const b = new Backoff();
    expect(b.mayRetry(t0), 'no failures → retry');
    b.recordFailure(t0);
    expect(!b.mayRetry(t0 + 4 * 60), '1st failure: not at 4m');
    expect(b.mayRetry(t0 + 5 * 60), '1st failure: ok at 5m');
    const base = t0 + 5 * 60;
    b.recordFailure(base);
    expect(!b.mayRetry(base + 9 * 60), '2nd: not at 9m');
    expect(b.mayRetry(base + 10 * 60), '2nd: ok at 10m');
    b.recordSuccess();
    expect(b.mayRetry(base), 'success resets');
});
suite('startIndex', () => {
    const times = Array.from({length: 24}, (_, h) => `2026-05-06T${String(h).padStart(2, '0')}:00`);
    eq(startIndex(times, '2026-05-06T14:30'), 14, '14:30');
    eq(startIndex(times, '2026-05-06T14:00'), 14, '14:00');
    eq(startIndex(times, '2026-05-06T00:15'), 0, '00:15');
    eq(startIndex(times, '2026-05-07T10:00'), 0, 'next day → 0');
    eq(startIndex(times, null), 0, 'null → 0');
    eq(startIndex([], '2026-05-06T14:00'), 0, 'empty → 0');
});
suite('labels', () => {
    eq(uvLabel(0), 'LOW', 'uv0'); eq(uvLabel(2), 'LOW', 'uv2'); eq(uvLabel(3), 'MODERATE', 'uv3');
    eq(uvLabel(5), 'MODERATE', 'uv5'); eq(uvLabel(6), 'HIGH', 'uv6'); eq(uvLabel(7), 'HIGH', 'uv7');
    eq(uvLabel(8), 'VERY HIGH', 'uv8'); eq(uvLabel(10), 'VERY HIGH', 'uv10'); eq(uvLabel(11), 'EXTREME', 'uv11');
    eq(aqiLabel(0), 'GOOD', 'aqi0'); eq(aqiLabel(50), 'GOOD', 'aqi50'); eq(aqiLabel(51), 'MODERATE', 'aqi51');
    eq(aqiLabel(150), 'UNHEALTHY (SENSITIVE)', 'aqi150'); eq(aqiLabel(200), 'UNHEALTHY', 'aqi200');
    eq(aqiLabel(300), 'VERY UNHEALTHY', 'aqi300'); eq(aqiLabel(301), 'HAZARDOUS', 'aqi301');
});
suite('isEurope', () => {
    expect(isEurope(51.5, -0.12), 'London'); expect(isEurope(59.3, 18.0), 'Stockholm');
    expect(!isEurope(37.77, -122.4), 'SF'); expect(!isEurope(35.68, 139.69), 'Tokyo');
});

// ---- NotificationPlannerTests ---------------------------------------------
const austin = makeLocation({id: '11111111-1111-1111-1111-111111111111', kind: LocationKind.SAVED, name: 'Austin', countryCode: 'US', latitude: 30.27, longitude: -97.74, timezoneIdentifier: 'America/Chicago'});
function snapshot({rainAlertMinutes = null, uvMax = null, alerts = [], sunrise = null, sunset = null} = {}) {
    return {
        location: austin, fetchedAt: Date.now() / 1000, unitsUsed: 0,
        utcOffsetSeconds: -5 * 3600, timezoneIdentifier: 'America/Chicago',
        rainAlertMinutes, uv: uvMax, uvMax, alerts, sunrise, sunset,
    };
}
const plan = (snap, settings, state, now) => planNotifications({snapshot: snap, settings, state, now});
suite('rainNotifiesOncePerEventAcrossRepeatRefreshes', () => {
    const settings = makeNotificationSettings({rainEnabled: true, rainLeadMinutes: 60});
    let state = new NotificationDedupState();
    let r = plan(snapshot({rainAlertMinutes: 120}), settings, state, iso('2026-07-18T14:00:00-05:00'));
    eq(r.fired.length, 0, '120 > 60 lead');
    r = plan(snapshot({rainAlertMinutes: 60}), settings, r.state, iso('2026-07-18T15:00:00-05:00'));
    eq(r.fired.map(f => f.kind).join(), 'rain', 'fires at 15:00');
    for (const [now, minutes] of [['2026-07-18T15:20:00-05:00', 60], ['2026-07-18T16:00:00-05:00', 15]]) {
        r = plan(snapshot({rainAlertMinutes: minutes}), settings, r.state, iso(now));
        eq(r.fired.length, 0, `deduped at ${now}`);
    }
    eq(Object.keys(r.state.fired).filter(k => k.startsWith('rain:')).length, 1, 'one rain key');
});
suite('rainReArmsForANewLaterEvent', () => {
    const settings = makeNotificationSettings({rainEnabled: true, rainLeadMinutes: 60});
    let r = plan(snapshot({rainAlertMinutes: 15}), settings, new NotificationDedupState(), iso('2026-07-18T15:00:00-05:00'));
    eq(r.fired.length, 1, 'event A');
    r = plan(snapshot({rainAlertMinutes: 60}), settings, r.state, iso('2026-07-18T19:00:00-05:00'));
    eq(r.fired.length, 1, 'event B');
    eq(Object.keys(r.state.fired).filter(k => k.startsWith('rain:')).length, 2, 'two rain keys');
});
suite('rainSuppressedBeyondLeadThreshold', () => {
    const r = plan(snapshot({rainAlertMinutes: 60}), makeNotificationSettings({rainEnabled: true, rainLeadMinutes: 30}), new NotificationDedupState(), iso('2026-07-18T14:00:00-05:00'));
    eq(r.fired.length, 0, '60 > 30');
});
suite('uvNotifiesOncePerDay', () => {
    const settings = makeNotificationSettings({uvEnabled: true, uvThreshold: 8});
    let r = plan(snapshot({uvMax: 9}), settings, new NotificationDedupState(), iso('2026-07-18T09:00:00-05:00'));
    eq(r.fired.map(f => f.kind).join(), 'uv', 'day 1 fires');
    r = plan(snapshot({uvMax: 9}), settings, r.state, iso('2026-07-18T10:30:00-05:00'));
    eq(r.fired.length, 0, 'same day deduped');
    r = plan(snapshot({uvMax: 9}), settings, r.state, iso('2026-07-19T09:00:00-05:00'));
    eq(r.fired.map(f => f.kind).join(), 'uv', 'next day fires');
});
suite('uvSuppressedAfterSolarNoon', () => {
    const snap = snapshot({uvMax: 10, sunrise: iso('2026-07-18T06:00:00-05:00'), sunset: iso('2026-07-18T20:00:00-05:00')});
    const r = plan(snap, makeNotificationSettings({uvEnabled: true, uvThreshold: 8}), new NotificationDedupState(), iso('2026-07-18T14:00:00-05:00'));
    eq(r.fired.length, 0, 'after solar noon');
});
suite('uvSuppressedBelowThreshold', () => {
    const r = plan(snapshot({uvMax: 7}), makeNotificationSettings({uvEnabled: true, uvThreshold: 8}), new NotificationDedupState(), iso('2026-07-18T09:00:00-05:00'));
    eq(r.fired.length, 0, 'below threshold');
});
suite('alertNotifiesOncePerIDAndSurvivesReload', () => {
    const settings = makeNotificationSettings({alertEnabled: true, alertMinSeverity: Severity.SEVERE});
    const alert = {id: 'urn:oid:xyz', event: 'Tornado Warning', severity: Severity.EXTREME, headline: 'Take cover now'};
    const r = plan(snapshot({alerts: [alert]}), settings, new NotificationDedupState(), iso('2026-07-18T12:00:00-05:00'));
    eq(r.fired.map(f => f.dedupKey).join(), 'alert:urn:oid:xyz', 'fires once');
    const reloaded = new NotificationDedupState(JSON.parse(JSON.stringify(r.state)));
    const r2 = plan(snapshot({alerts: [alert]}), settings, reloaded, iso('2026-07-18T13:00:00-05:00'));
    eq(r2.fired.length, 0, 'seen-set survives reload');
});
suite('alertSeverityGates', () => {
    const moderate = {id: 'm1', event: 'Flood Advisory', severity: Severity.MODERATE};
    let r = plan(snapshot({alerts: [moderate]}), makeNotificationSettings({alertEnabled: true, alertMinSeverity: Severity.SEVERE}), new NotificationDedupState(), iso('2026-07-18T12:00:00-05:00'));
    eq(r.fired.length, 0, 'moderate below severe');
    r = plan(snapshot({alerts: [moderate]}), makeNotificationSettings({alertEnabled: true, alertMinSeverity: Severity.MODERATE}), new NotificationDedupState(), iso('2026-07-18T12:00:00-05:00'));
    eq(r.fired.map(f => f.kind).join(), 'alert', 'moderate opt-in');
});
suite('disabledTriggersFireNothing', () => {
    const snap = snapshot({rainAlertMinutes: 10, uvMax: 11, alerts: [{id: 'x', event: 'Warning', severity: Severity.EXTREME}]});
    const r = plan(snap, makeNotificationSettings(), new NotificationDedupState(), iso('2026-07-18T09:00:00-05:00'));
    eq(r.fired.length, 0, 'all off');
});
suite('pruneCapsAtMaxEvictingOldest', () => {
    const state = new NotificationDedupState();
    const base = 1_700_000_000;
    for (let i = 0; i < 201; i++) state.record(`alert:${i}`, base + i);
    state.prune(base + 300);
    eq(Object.keys(state.fired).length, 200, 'capped at 200');
    eq(state.has('alert:0'), false, 'oldest evicted');
    eq(state.has('alert:200'), true, 'newest kept');
});
suite('pruneDropsExpiredFirst', () => {
    const state = new NotificationDedupState();
    const now = 1_700_000_000;
    state.record('alert:old', now - NotificationDedupState.expiryAge - 1);
    state.record('alert:fresh', now - 60);
    state.prune(now);
    eq(state.has('alert:old'), false, 'expired dropped');
    eq(state.has('alert:fresh'), true, 'fresh kept');
});
suite('planPrunesExpiredWhileRecordingNew', () => {
    const now = iso('2026-07-18T12:00:00-05:00');
    const state = new NotificationDedupState();
    state.record('alert:ancient', now - NotificationDedupState.expiryAge - 1);
    const r = plan(snapshot({alerts: [{id: 'new', event: 'Severe Thunderstorm Warning', severity: Severity.SEVERE}]}),
        makeNotificationSettings({alertEnabled: true, alertMinSeverity: Severity.SEVERE}), state, now);
    eq(r.fired.length, 1, 'new fires');
    eq(r.state.has('alert:ancient'), false, 'ancient pruned');
    eq(r.state.has('alert:new'), true, 'new recorded');
});

// ---- LocationsFile ---------------------------------------------------------
const saved = (name, lat, lon) => makeLocation({kind: LocationKind.SAVED, name, latitude: lat, longitude: lon});
suite('locationsFile', () => {
    let file = new LocationsFile();
    eq(file.locations.length, 0, 'empty');
    eq(file.activeLocationID, null, 'no active');
    const id = file.add(saved('Paris', 48.85, 2.35));
    eq(file.saved.length, 1, 'one saved');
    eq(file.activeLocationID, id, 'first save active');

    file = new LocationsFile();
    const first = file.add(saved('Paris', 48.8566, 2.3522));
    const again = file.add(saved('Paris', 48.8566, 2.3522));
    eq(file.saved.length, 1, 'dedupe by coords');
    eq(again, first, 'dup returns existing id');
    file.add(saved('Boulogne', 48.8352, 2.2409));
    eq(file.saved.length, 2, 'nearby distinct kept');

    file = new LocationsFile();
    const paris = file.add(saved('Paris', 48.85, 2.35));
    const tokyo = file.add(saved('Tokyo', 35.68, 139.69));
    file.setActive(tokyo);
    eq(file.remove(tokyo), true, 'remove tokyo');
    eq(file.saved.map(l => l.name).join(), 'Paris', 'survivor');
    eq(file.activeLocationID, paris, 'active reassigned');
    eq(file.remove(paris), true, 'remove paris');
    eq(file.locations.length, 0, 'all gone');
    eq(file.activeLocationID, null, 'no fallback city');

    file = new LocationsFile();
    file.add(saved('Paris', 48.85, 2.35));
    file.upsertCurrentLocation({latitude: 37.77, longitude: -122.41, name: 'San Francisco'});
    eq(file.locations[0].kind, LocationKind.CURRENT, 'current pinned first');
    eq(file.remove(file.currentLocation.id), false, 'current not deletable');
    file.upsertCurrentLocation({latitude: 37.78, longitude: -122.40});
    eq(file.currentLocation.name, 'San Francisco', 'nil name keeps last');
    eq(file.locations.filter(l => l.kind === LocationKind.CURRENT).length, 1, 'still one pinned');

    const roundTrip = new LocationsFile(JSON.parse(JSON.stringify(file)));
    eq(roundTrip.locations.length, file.locations.length, 'JSON round-trip');
});

// ---- NWS alert mapping -----------------------------------------------------
suite('nwsAlertMapping', () => {
    const f = fixture('nws-alerts');
    const alerts = (f.features ?? []).map(x => alertFromProperties(x.properties)).filter(a => a);
    expect(alerts.length > 0, 'fixture yields alerts');
    const a = alerts[0];
    expect(typeof a.id === 'string' && a.id.length > 0, 'id');
    expect(a.severity >= Severity.UNKNOWN && a.severity <= Severity.EXTREME, 'severity enum');
    expect(a.onset === null || typeof a.onset === 'number', 'onset parsed');
    eq(alertFromProperties({event: 'x'}), null, 'no id → dropped');
});

// ---- Radar tile math -------------------------------------------------------
suite('radarTileMath', () => {
    const base = RadarTileMath.basePlan(37.7749, -122.4194);
    eq(base.zoom, 10, 'base zoom (512 px reference)');
    eq(base.placements.length, 9, '3×3 basemap window');
    for (const p of base.placements) eq(p.destSize, 512, 'base tile 512px');
    const esri = RadarTileMath.basePlan(37.7749, -122.4194, RadarTileMath.outputSize, 11);
    eq(esri.zoom, 11, 'esri zoom');
    expect(esri.placements.length >= 16 && esri.placements.length <= 25, `z11/256 window is 4–5 tiles across (${esri.placements.length})`);
    for (const p of esri.placements) eq(p.destSize, 256, 'esri tile 256px');
    // Every placement covers the window edge-to-edge in both plans.
    for (const plan of [base, esri]) {
        const minX = Math.min(...plan.placements.map(p => p.destX)), maxX = Math.max(...plan.placements.map(p => p.destX + p.destSize));
        expect(minX <= 0 && maxX >= RadarTileMath.outputSize, `plan z${plan.zoom} spans the window (${minX}..${maxX})`);
    }
    const radar = RadarTileMath.radarPlan(37.7749, -122.4194);
    eq(radar.zoom, 7, 'radar zoom');
    expect(radar.placements.length >= 1 && radar.placements.length <= 4, `radar 1–4 tiles (${radar.placements.length})`);
    for (const p of radar.placements) eq(p.destSize, 4096, 'radar tile upsampled 8×');
    const xy = RadarTileMath.lonLatToTileXY(0, 0, 1);
    eq(xy.x, 1, 'lon 0 → x 1 at z1'); eq(xy.y, 1, 'lat 0 → y 1 at z1');
});

// ---- run -------------------------------------------------------------------
for (const [name, fn] of suites) {
    const before = failed;
    try {
        fn();
    } catch (e) {
        failed++;
        failures.push(`${name}: threw ${e.message}\n${e.stack}`);
    }
    print(`${failed === before ? '✔' : '✘'} ${name}`);
}
print(`\n${passed} expectations passed, ${failed} failed across ${suites.length} suites`);
for (const f of failures) print(`  FAIL ${f}`);
if (failed > 0) imports.system.exit(1);
